# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

target 'MobileAppwithPushNotificationsC4CCOVID19' do
    pod 'BMSCore', '~> 2.0'
    pod 'BMSPush', '~> 3.0'
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'IBMCloudAppID'

  # Pods for MobileAppwithPushNotificationsC4CCOVID19

  target 'MobileAppwithPushNotificationsC4CCOVID19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileAppwithPushNotificationsC4CCOVID19UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
